services:
  - type: web
    name: doccraft-backend
    env: java
    rootDir: Backend
    buildCommand: mvn clean install -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://sql12.freesqldatabase.com:3306/sql12819570
      - key: SPRING_DATASOURCE_USERNAME
        value: sql12819570
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false