export const COLORS = {
  bg: "#0D0D0F",
  bgCard: "#141416",
  bgHover: "#1a1a1d",
  border: "#232326",
  borderHover: "#3a3a3f",
  text: "#F0EDE6",
  textMuted: "#888",
  textDim: "#555",
  accent: "#4F8EF7",
  accentPurple: "#A14FF7",
  success: "#5BBF7A",
  warning: "#F7A94F",
  danger: "#E85D4A",
};

export const TOOLS = [
  {
    id: "pdf-to-word",
    icon: "📄",
    iconTo: "📝",
    label: "PDF to Word",
    desc: "Convert PDF files to editable Word documents",
    from: "PDF",
    to: "DOCX",
    accept: ".pdf",
    color: "#4F8EF7",
    category: "convert",
  },
  {
    id: "word-to-pdf",
    icon: "📝",
    iconTo: "📄",
    label: "Word to PDF",
    desc: "Transform Word documents into PDF format",
    from: "DOCX",
    to: "PDF",
    accept: ".docx,.doc",
    color: "#E85D4A",
    category: "convert",
  },
  {
    id: "pdf-to-jpg",
    icon: "📄",
    iconTo: "🖼️",
    label: "PDF to JPG",
    desc: "Extract pages from PDF as high-quality images",
    from: "PDF",
    to: "JPG",
    accept: ".pdf",
    color: "#F7A94F",
    category: "convert",
  },
  {
    id: "jpg-to-pdf",
    icon: "🖼️",
    iconTo: "📄",
    label: "JPG to PDF",
    desc: "Combine images into a single PDF document",
    from: "JPG/PNG",
    to: "PDF",
    accept: ".jpg,.jpeg,.png,.webp",
    color: "#5BBF7A",
    category: "convert",
  },
  {
    id: "merge-pdf",
    icon: "🔗",
    iconTo: "📄",
    label: "Merge PDF",
    desc: "Combine multiple PDF files into one document",
    from: "PDFs",
    to: "PDF",
    accept: ".pdf",
    color: "#A14FF7",
    category: "organize",
    multi: true,
  },
  {
    id: "split-pdf",
    icon: "✂️",
    iconTo: "📄",
    label: "Split PDF",
    desc: "Separate a PDF into individual pages or ranges",
    from: "PDF",
    to: "PDFs",
    accept: ".pdf",
    color: "#F74FAB",
    category: "organize",
  },
  {
    id: "compress-pdf",
    icon: "🗜️",
    iconTo: "📄",
    label: "Compress PDF",
    desc: "Reduce PDF file size while keeping quality",
    from: "PDF",
    to: "PDF",
    accept: ".pdf",
    color: "#4FC8F7",
    category: "optimize",
  },
  {
    id: "pdf-to-excel",
    icon: "📄",
    iconTo: "📊",
    label: "PDF to Excel",
    desc: "Convert PDF tables into Excel spreadsheets",
    from: "PDF",
    to: "XLSX",
    accept: ".pdf",
    color: "#5BBF7A",
    category: "convert",
  },
  {
    id: "rotate-pdf",
    icon: "🔄",
    iconTo: "📄",
    label: "Rotate PDF",
    desc: "Rotate pages in your PDF document",
    from: "PDF",
    to: "PDF",
    accept: ".pdf",
    color: "#F7A94F",
    category: "organize",
  },
  {
    id: "protect-pdf",
    icon: "🔒",
    iconTo: "📄",
    label: "Protect PDF",
    desc: "Encrypt your PDF with a password",
    from: "PDF",
    to: "PDF",
    accept: ".pdf",
    color: "#E85D4A",
    category: "security",
  },
  {
    id: "unlock-pdf",
    icon: "🔓",
    iconTo: "📄",
    label: "Unlock PDF",
    desc: "Remove password protection from a PDF",
    from: "PDF",
    to: "PDF",
    accept: ".pdf",
    color: "#5BBF7A",
    category: "security",
  },
];

export const CATEGORIES = [
  { id: "all", label: "All Tools" },
  { id: "convert", label: "Convert" },
  { id: "organize", label: "Organize" },
  { id: "optimize", label: "Optimize" },
  { id: "security", label: "Security" },
];